---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/juaneysuchicha.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_juaneysuchicha/
      - /bin/rsync -av ./ $DEPLOYPATH

